name: Build CI Buildbox Images
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  buildbox-gha:
    name: Build Ubuntu Buildbox on GHA
    runs-on: ubuntu-22.04-32
    defaults:
      run:
        working-directory: upstream

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          driver: docker

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build buildbox image
        run: cd build.assets && make buildbox

  buildbox-depot:
    name: Build Ubuntu Buildbox on Depot
    runs-on: depot-ubuntu-22.04-32
    defaults:
      run:
        working-directory: upstream

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: depot/setup-action@v1

      - name: Determine Toolchain Versions and cache paths
        run: |
          echo NODE_VERSION=$(make -s -C build.assets print-node-version) >> $GITHUB_ENV
          echo GOLANG_VERSION=$(make -s -C build.assets print-go-version) >> $GITHUB_ENV
          echo RUST_VERSION=$(make -s -C build.assets print-rust-version) >> $GITHUB_ENV
          echo WASM_PACK_VERSION=$(make -s -C build.assets print-wasm-pack-version) >> $GITHUB_ENV
          echo GOLANGCI_LINT_VERSION=$(make -s -C build.assets print-golangci-lint-version) >> $GITHUB_ENV
          echo BUF_VERSION=$(make -s -C build.assets print-buf-version) >> $GITHUB_ENV
          echo BUILDBOX=$(make -s -C build.assets show-buildbox-base-image) >> $GITHUB_ENV
          echo UID=$(id -u) >> $GITHUB_ENV
          echo GID=$(id -g) >> $GITHUB_ENV

      # We need to keep env vars in sync, so, we can't use standard build actions
      - name: Build buildbox image
        # Changingn the docker buildx build command from cd build.assets && make buildbox to depot build version
        run: |
          cd build.assets && depot build --project glxrppp990 \
          --build-arg UID=${{ env.UID }} \
          --build-arg GID=${{ env.GID }} \
          --build-arg GOLANG_VERSION=${{ env.GOLANG_VERSION }} \
          --build-arg GOLANGCI_LINT_VERSION=${{ env.GOLANGCI_LINT_VERSION }} \
          --build-arg RUST_VERSION=${{ env.RUST_VERSION }} \
          --build-arg WASM_PACK_VERSION=${{ env.WASM_PACK_VERSION }} \
          --build-arg NODE_VERSION=${{ env.NODE_VERSION }} \
          --build-arg LIBBPF_VERSION=1.2.2 \
          --build-arg BUF_VERSION=${{ env.BUF_VERSION }} \
          --build-arg GOGO_PROTO_TAG=v1.3.2 \
          --build-arg NODE_GRPC_TOOLS_VERSION=1.12.4 \
          --build-arg NODE_PROTOC_TS_VERSION=5.0.1 \
          --build-arg PROTOC_VERSION=26.1 \
          --cache-to type=inline \
          --cache-from ${{ env.BUILDBOX }} \
          --load \
          --tag ${{ env.BUILDBOX }} .
